config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_member!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('updated_at ASC')
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:post)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Members-Only</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Post', new_post_path, class: "button is-info is-inverted"%>
            </p>
            <% if member_signed_in? %>
              <p class="control">
                <%= link_to current_member.name, edit_member_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_member_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_member_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_member_registration_path, class: "button is-info" %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_feed.html.erb
<div class="column is-half">
  <% if member_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is=64x64">
          <%= gravatar_image_tag(current_member.email, size: 64, alt: current_member.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render 'posts/form' %>
      </div>
    </article>
  <% end %>

  <% @posts.each do |post| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(post.member.email, size: 64, alt: post.member.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p><%= post.post %></p>
            <% if member_signed_in? %>
              <strong><%= post.member.name %> </strong><br />
            <% end %>
            <p class="date_created">Created at: <%= post.created_at.to_s[0..-5] %> </p>
          </div>
          <% if member_signed_in? && current_member.id == post.member_id %>
            <nav class="level is-mobile">
              <div class="level-left">
                <%= link_to post, class: "level-item" do %>
                  <span class="icon is-small"><i class="fa fa-reply"></i></span>
                <% end %>
                <%= link_to edit_post_path(post), class: "level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>

</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :post, label: "Post about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new post...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'feed' %>

app/views/posts/new.html.erb
<div class="column is-half">
  <div class="box">
  <h1>New Post</h1>
  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="column is-half">
  <div class="box">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Post:</strong>
      <%= @post.post %>
    </p>

    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', posts_path %>
  </div>
</div>